### ISSUE TITLE
大佬有群吗？提示这样的错误咋整好

### ISSUE THREAD

**Issue by 1348182031** [wangwangit/liantong#1]
>>>签到看视频，下载APP流量奖励任务完成！
('>>>\xe9\x87\x91\xe5\xb8\x81\xe6\x8a\xbd\xe5\xa5\x96\xef\xbc\x9a', u'\u7528\u6237\u673a\u4f1a\u6b21\u6570\u4e0d\u8db3')
('>>>\xe9\x87\x91\xe5\xb8\x81\xe6\x8a\xbd\xe5\xa5\x96\xef\xbc\x9a', u'\u7528\u6237\u673a\u4f1a\u6b21\u6570\u4e0d\u8db3')
('>>>\xe9\x87\x91\xe5\xb8\x81\xe6\x8a\xbd\xe5\xa5\x96\xef\xbc\x9a', u'\u7528\u6237\u673a\u4f1a\u6b21\u6570\u4e0d\u8db3')
Traceback (most recent call last):
  File "/home/liantong/sign1.py", line 212, in <module>
    tgPush(user.resp)
  File "/home/liantong/sign1.py", line 204, in tgPush
    post(telegram_url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bote5dae66e9bd3e33ecacb1dacb667b751a7f3eb670d31a98adb6e12d45ab86629/sendMessage?chat_id=%E8%81%94%E9%80%9A&text=%E8%81%94%E9%80%9A%E8%90%A5%E4%B8%9A%E5%8E%85%E7%AD%BE%E5%88%B0%E9%80%9A%E7%9F%A5+%0A%0A%3E%3E%3E%E8%8E%B7%E5%8F%96%E7%99%BB%E5%BD%95%E7%8A%B6%E6%80%81%E6%88%90%E5%8A%9F%EF%BC%81%0A%0A%3E%3E%3E%E7%AD%BE%E5%88%B0%E5%89%8D%E7%A7%AF%E5%88%86%EF%BC%9A9050%0A%0A%3E%3E%3E%E4%BB%8A%E5%A4%A9%E5%B7%B2%E7%AD%BE%E5%88%B0%EF%BC%81%0A%0A%3E%3E%3E%E7%A7%AF%E5%88%86%E7%BF%BB%E5%80%8D%E6%88%90%E5%8A%9F%EF%BC%81%0A%0A%3E%3E%3E%E7%AD%BE%E5%88%B0%E5%90%8E%E7%A7%AF%E5%88%86%EF%BC%9A9050%0A%0A%3E%3E%3E1G%E6%B5%81%E9%87%8F%E6%97%A5%E5%8C%85%E9%A2%86%E5%8F%96%E6%88%90%E5%8A%9F%EF%BC%81%0A%0A%3E%3E%3E%E6%AF%8F%E6%97%A5%E6%89%93%E5%8D%A1%EF%BC%9A%E4%BB%8A%E5%A4%A9%E5%B7%B2%E6%89%93%E5%8D%A1%0A%0A%3E%3E%3E%E6%AF%8F%E6%97%A5%E6%B5%87%E6%B0%B4%EF%BC%9Asuccess%0A%0A%3E%3E%3E%E9%87%91%E5%B8%81%E6%8A%BD%E5%A5%96%EF%BC%9A%E7%94%A8%E6%88%B7%E6%9C%BA%E4%BC%9A%E6%AC%A1%E6%95%B0%E4%B8%8D%E8%B6%B3%0A%0A%3E%3E%3E%E9%87%91%E5%B8%81%E6%8A%BD%E5%A5%96%EF%BC%9A%E7%94%A8%E6%88%B7%E6%9C%BA%E4%BC%9A%E6%AC%A1%E6%95%B0%E4%B8%8D%E8%B6%B3%0A%0A%3E%3E%3E%E9%87%91%E5%B8%81%E6%8A%BD%E5%A5%96%EF%BC%9A%E7%94%A8%E6%88%B7%E6%9C%BA%E4%BC%9A%E6%AC%A1%E6%95%B0%E4%B8%8D%E8%B6%B3%0A%0A&parse_mode=Html&disable_web_page_preview=yes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2b51450>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by wangwangit** [comment]
这个是TG推送得问题吧.你把tg推送那块得代码屏蔽掉就可以了.   最后 tgPush(user.resp) 这句删除掉

**Comment by 1348182031** [comment]
Traceback (most recent call last):
  File "/home/liantong/sign.py", line 210, in <module>
    tgPush(user.resp)
  File "/home/liantong/sign.py", line 202, in tgPush
    post(telegram_url, params=params)
NameError: global name 'post' is not defined

**Comment by 1348182031** [comment]
大佬给个QQ群行吗

**Comment by wangwangit** [comment]
没有qq群耶..我新提交勒一个文件,你用另外一个文件试试.我取消勒推送

**Comment by 1348182031** [comment]
我看你另外一个文件是直接取消了推送，所以我就直接删了就完事了。大佬能加一下你QQ或者微信吗？小白想跟你混，我也有一些撸毛的信息，回头可以分享下……

**Comment by wangwangit** [comment]
3292948523
