### ISSUE TITLE
WIN10，python3.7 运行不成功

### ISSUE THREAD

**Issue by cont55** [wangwangit/liantong#2]
>>>每日浇水： success
>>>签到看视频，下载APP流量奖励任务开始...
>>>签到看视频，下载APP流量奖励任务完成！
Traceback (most recent call last):
  File "no.py", line 197, in <module>
    user.daytask()  # 日常任务
  File "no.py", line 187, in daytask
    print(">>>金币抽奖：", res8.json()['RspMsg'])
  File "C:\Python\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 30 column 1 (char 29)

**Comment by wangwangit** [comment]
我也刚学py。😂😂可能帮你解决不了。
